USE [master]
GO

/****** Object:  Database [CSharpTest]    Script Date: 11/03/2015 13:22:08 ******/
CREATE DATABASE [CSharpTest] ON  PRIMARY 
( NAME = N'CSharpTest', FILENAME = N'D:\SQL\DATA\CSharpTest.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CSharpTest_log', FILENAME = N'D:\SQL\DATA\CSharpTest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CSharpTest] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CSharpTest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CSharpTest] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CSharpTest] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CSharpTest] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CSharpTest] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CSharpTest] SET ARITHABORT OFF 
GO

ALTER DATABASE [CSharpTest] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CSharpTest] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [CSharpTest] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CSharpTest] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CSharpTest] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CSharpTest] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CSharpTest] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CSharpTest] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CSharpTest] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CSharpTest] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CSharpTest] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CSharpTest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CSharpTest] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CSharpTest] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CSharpTest] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CSharpTest] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CSharpTest] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CSharpTest] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CSharpTest] SET  READ_WRITE 
GO

ALTER DATABASE [CSharpTest] SET RECOVERY FULL 
GO

ALTER DATABASE [CSharpTest] SET  MULTI_USER 
GO

ALTER DATABASE [CSharpTest] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CSharpTest] SET DB_CHAINING OFF 
GO


